### ISSUE TITLE
Window is too large

### ISSUE THREAD

**Issue by beckrd** [RaymondPackbier/PixInSight_AnnotationFrame#1]
I have tried this script on two different Limux machines running at 1920x1080.  On both systems, the normal window cuts off everything below Line 2 under the image.  Maximizing the script window exposes Line 3 but anything below that is obscured.

**Comment by beckrd** [comment]
I was able to test this out by Alt-clicking on the window and moving it up.  Resizing works from left to right but not  up and down.

**Comment by RaymondPackbier** [comment]
Hi Beckrd,

I will work on the rescaling of the window and put a new version to test
online.

Thanks for the feedback!

CS,
Ray

**Comment by RaymondPackbier** [comment]
This should be fixed in version 0.21, could you please verify?
I changed the size of the UI elements to accommodate smaller screens
