### ISSUE TITLE
No dropdown boxes for fonts

### ISSUE THREAD

**Issue by beckrd** [RaymondPackbier/PixInSight_AnnotationFrame#2]
On the Linux machines where I have tested this script, there are no dropdowns for the fonts.

**Comment by beckrd** [comment]
Correction of the two machines, one did have a dropdown box.  The other didn't

**Comment by RaymondPackbier** [comment]
I did a visual check of the code and could find no apparent reason for the missing dropbox. Unfortunately I do not have a linux environment at hand to try to reproduce this.
Could you check if the standard script Render/Drawsignature is working on that machine? It uses the same dropbox mechanism.

**Comment by beckrd** [comment]
Don't know if this is the difference or not, but the time I didn't get dropdown  boxes, I had the script in PixInsight's script folder.  When I cloned the repository to my home folder and ran the script from there, I had dropdown boxes.  Go ahead and mark this closed.
